import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css'
import "./globals.css";
import BootstrapClient from "./components/BootstrapClient";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NextPostgresSql",
  description: "Generated by Hyconcode",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}
        data-new-gr-c-s-check-loaded="14.1092.0"
        data-gr-ext-installed=""
      >
        <Navbar />
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
